In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10], [15,20]]

In [3]:
my_matrix[0]

[5, 10]

In [4]:
my_matrix[1]

[15, 20]

In [9]:
my_matrix[0][1]

10

In [10]:
my_matrix[1][1]

20

In [11]:
#row - column

In [18]:
numpy_matrix = np.array([[5,10],[15,20]])

In [19]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [20]:
numpy_matrix[1][0]

np.int64(15)

In [21]:
numpy_matrix.sum()

np.int64(50)

In [22]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.zeros((1,2))

array([[0., 0.]])

In [35]:
# matrix arithmetic

In [36]:
first_array = np.array([[10,20], [30,40]])

In [57]:
first_array 

array([[10, 20],
       [30, 40]])

In [38]:
second_array = np.array([[30,40], [40,50]])

In [40]:
first_array + second_array

array([[40, 60],
       [70, 90]])

In [41]:
first_array

array([[10, 20],
       [30, 40]])

In [44]:
third_array= np.array([[60,40]])

In [45]:
third_array

array([[60, 40]])

In [46]:
first_array + third_array

array([[70, 60],
       [90, 80]])

In [76]:
fourth_array = np.array([[10,20,30,40,50]])

In [77]:
fourth_array

array([[10, 20, 30, 40, 50]])

In [78]:
#first_array + fourth_array #broadcaste uymaz

In [79]:
first_array * 2

array([[20, 40],
       [60, 80]])

In [80]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [81]:
third_array = np.array([[10],[20]])

In [82]:
third_array

array([[10],
       [20]])

In [83]:
third_array.shape

(2, 1)

In [67]:
first_array.shape

(2, 2)

In [86]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [87]:
first_array

array([[10, 20],
       [30, 40]])

In [88]:
#matrix multiplication

In [89]:
first_array

array([[10, 20],
       [30, 40]])

In [90]:
second_array

array([[30, 40],
       [40, 50]])

In [91]:
first_array * second_array

array([[ 300,  800],
       [1200, 2000]])

In [93]:
#dot product column sayısı ile row sayısı eşit olcak

In [96]:
first_matrix = np.array([[10,20,30]])

In [97]:
first_matrix

array([[10, 20, 30]])

In [98]:
first_matrix.shape

(1, 3)

In [99]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [100]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [102]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [103]:
second_matrix.shape

(3, 2)

In [104]:
#first_matrix * second_matrix

In [105]:
result_matrix = first_matrix.dot(second_matrix)

In [106]:
result_matrix

array([[120, 180]])

In [107]:
result_matrix.shape

(1, 2)